export const Title3D = 'OBJECTOS 3D'
export const TitleDevelopers = 'DEVELOPERS'
export const TitleCinteolt = 'CINTEOLT'
export const TitleSchoolBook = 'SCHOOL BOOK'
export const TitleCrud = 'POS SYSTEM'
export const UrlImg = '/JesusEcheverria.github.io/Images/LogoHerramientas/'